<?php

use Illuminate\Database\Seeder;

class StatesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('states')->delete();
        
        \DB::table('states')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Abia',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-201815.270995abia.jpg',
                'code' => 'AB',
                'longitude' => '5.4527',
                'latitude' => '7.5248',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Adamawa',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-201836.984376adamawa.png',
                'code' => 'AD',
                'longitude' => '9.3265',
                'latitude' => '12.3984',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Akwa Ibom',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-201906.150342akwa-ibom.png',
                'code' => 'AK',
                'longitude' => '4.9057',
                'latitude' => '7.8537',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Anambra',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-201925.669234anambra.jpg',
                'code' => 'AN',
                'longitude' => '6.2209',
                'latitude' => '6.9370',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Bauchi',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-201948.062480bauchi.png',
                'code' => 'BA',
                'longitude' => '10.3010',
                'latitude' => '9.8237',
                'total_case' => 2,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 1,
                'index_cases' => 1,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 06:55:26',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Bayelsa',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202007.838236bayelsa.jpg',
                'code' => 'BY',
                'longitude' => '4.7719',
                'latitude' => '6.0699',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Benue',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202027.053491benue.jpg',
                'code' => 'BE',
                'longitude' => '7.3369',
                'latitude' => '8.7404',
                'total_case' => 1,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 1,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 15:16:25',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Borno',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202048.144550borno.gif',
                'code' => 'BR',
                'longitude' => '11.8846',
                'latitude' => '13.1520',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Cross River',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202105.760591cross-river.jpg',
                'code' => 'CR',
                'longitude' => '5.8702',
                'latitude' => '8.5988',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Delta',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202125.012506delta.jpg',
                'code' => 'DE',
                'longitude' => '5.7040',
                'latitude' => '5.9339',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Ebonyi',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202146.414287ebonyi.png',
                'code' => 'EB',
                'longitude' => '6.2649',
                'latitude' => '8.0137',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Edo',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202205.102453edo.jpg',
                'code' => 'ED',
                'longitude' => '6.6342',
                'latitude' => '5.9304',
                'total_case' => 2,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 2,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 07:07:04',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Ekiti',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202232.890403ekiti.jpg',
                'code' => 'EK',
                'longitude' => '7.7190',
                'latitude' => '5.3110',
                'total_case' => 1,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 1,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Enugu',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202252.869433enugu.png',
                'code' => 'EN',
                'longitude' => '6.4584',
                'latitude' => '7.5464',
                'total_case' => 2,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 2,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 07:06:45',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'FCT, Abuja',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202313.225826fct-abuja.jpeg',
                'code' => 'FC',
                'longitude' => '9.0765',
                'latitude' => '7.3986',
                'total_case' => 14,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 14,
                'index_cases' => 7,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 07:04:37',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Gombe',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202334.211943gombe.jpg',
                'code' => 'GO',
                'longitude' => '10.2791',
                'latitude' => '11.1731',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Imo',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202354.223702imo.jpg',
                'code' => 'IM',
                'longitude' => '5.5720',
                'latitude' => '7.0588',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Jigawa',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202415.741113jigawa.jpeg',
                'code' => 'JI',
                'longitude' => '12.2280',
                'latitude' => '9.5616',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Kaduna',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202447.919101kaduna.png',
                'code' => 'KD',
                'longitude' => '10.5105',
                'latitude' => '7.4165',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Kano',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202507.133586kano.jpeg',
                'code' => 'KN',
                'longitude' => '12.0022',
                'latitude' => '8.5920',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Katsina',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202527.915080katsina.png',
                'code' => 'KT',
                'longitude' => '12.9816',
                'latitude' => '7.6223',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Kebbi',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202551.565545kebbi.png',
                'code' => 'KB',
                'longitude' => '11.4942',
                'latitude' => '4.2333',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Kogi',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202616.865362kogi.png',
                'code' => 'KO',
                'longitude' => '7.7337',
                'latitude' => '6.6906',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Kwara',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202635.947066kwara.jpg',
                'code' => 'KW',
                'longitude' => '8.9669',
                'latitude' => '4.3874',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Lagos',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202654.138489lagos.jpg',
                'code' => 'LA',
                'longitude' => '6.5244',
                'latitude' => '3.3792',
                'total_case' => 59,
                'deaths' => 1,
                'recoveries' => 2,
                'active_cases' => 56,
                'index_cases' => 34,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 15:16:11',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Nasarawa',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202715.561181nassarawa.jpg',
                'code' => 'NA',
                'longitude' => '8.4998',
                'latitude' => '8.1997',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Niger',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202733.261135niger.jpg',
                'code' => 'NI',
                'longitude' => '9.9309',
                'latitude' => '5.5983',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Ogun',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202748.986707ogun.jpg',
                'code' => 'OG',
                'longitude' => '6.9980',
                'latitude' => '3.4737',
                'total_case' => 3,
                'deaths' => 0,
                'recoveries' => 1,
                'active_cases' => 2,
                'index_cases' => 1,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 06:54:29',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Ondo',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202803.295326ondo.jpg',
                'code' => 'OD',
                'longitude' => '6.9149',
                'latitude' => '5.1478',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Osun',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202818.833978osun.jpg',
                'code' => 'OS',
                'longitude' => '7.5629',
                'latitude' => '4.5200',
                'total_case' => 1,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 1,
                'index_cases' => 1,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 06:56:20',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Oyo',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202838.411470oyo.jpg',
                'code' => 'OY',
                'longitude' => '8.1574',
                'latitude' => '3.6147',
                'total_case' => 3,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 3,
                'index_cases' => 1,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 07:04:47',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Plateau',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202855.975948plateau.jpg',
                'code' => 'PL',
                'longitude' => '9.2182',
                'latitude' => '9.5179',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Rivers',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202912.622972rivers.jpg',
                'code' => 'RI',
                'longitude' => '4.8396',
                'latitude' => '6.9112',
                'total_case' => 1,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 1,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 06:57:55',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Sokoto',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202929.156780sokoto.jpg',
                'code' => 'SO',
                'longitude' => '13.0533',
                'latitude' => '5.3223',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Taraba',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-202945.659378taraba.jpg',
                'code' => 'TA',
                'longitude' => '7.9994',
                'latitude' => '10.7740',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Yobe',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-203001.804056yobe.jpg',
                'code' => 'YO',
                'longitude' => '12.2939',
                'latitude' => '11.4390',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Zamfara',
                'image' => 'https://grid3.gov.ng/uploads/group/2019-04-15-203017.300705zamfara.jpg',
                'code' => 'ZM',
                'longitude' => '12.1222',
                'latitude' => '6.2236',
                'total_case' => 0,
                'deaths' => 0,
                'recoveries' => 0,
                'active_cases' => 0,
                'index_cases' => 0,
                'contact_cases' => 0,
                'tracing_index' => 0,
                'tracing_contact' => 0,
                'tracing_cases' => 0,
                'country_id' => 1,
                'boundary' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}